apiVersion: v1
kind: Service
metadata:
  name: tourlist-common-kafka-service
spec:
  selector:
    app: tourlist-common-kafka-pod
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: tourlist-common-kafka-service
spec:
  selector:
    app: tourlist-common-zookeeper-pod
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tourlist-common-kafka-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tourlist-common-zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-common-kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourlist-common-kafka-pod
  template:
    metadata:
      labels:
        app: tourlist-common-kafka-pod
    spec:
      containers:
        - name: tourlist-common-kafka
          image: bitnami/kafka:3.6
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: tourlist-common-kafka-volume
              mountPath: /bitnami/kafka
          envFrom:
            - configMapRef:
                name: tourlist-common-kafka-config
      volumes:
        - name: tourlist-common-kafka-volume
          persistentVolumeClaim:
            claimName: tourlist-common-kafka-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-common-zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourlist-common-zookeeper-pod
  template:
    metadata:
      labels:
        app: tourlist-common-zookeeper-pod
    spec:
      containers:
        - name: tourlist-common-zookeeper
          image: bitnami/zookeeper:3.8.3
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: tourlist-common-zookeeper-volume
              mountPath: /bitnami/kafka
          envFrom:
            - configMapRef:
                name: tourlist-common-kafka-config
      volumes:
        - name: tourlist-common-zookeeper-volume
          persistentVolumeClaim:
            claimName: tourlist-common-zookeeper-pvc