apiVersion: v1
kind: ConfigMap
metadata:
  name: tourlist-common-kafka-config
data:
  ALLOW_ANONYMOUS_LOGIN: "yes"
  KAFKA_ZOOKEEPER_CONNECT: "tourlist-common-zookeeper-service:2181"
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:9093"
  KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://tourlist-common-kafka-service:9092,EXTERNAL://tourlist-common-kafka-service:9093"
  KAFKA_INTER_BROKER_LISTENER_NAME: "CLIENT"
  ALLOW_PLAINTEXT_LISTENER: "yes"