apiVersion: v1
kind: Service
metadata:
  name: tourlist-payment-db-service
spec:
  selector:
    app: tourlist-payment-mongodb-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tourlist-payment-mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tourlist-payment-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-payment-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourlist-payment-mongodb-pod
  template:
    metadata:
      labels:
        app: tourlist-payment-mongodb-pod
    spec:
      containers:
        - name: tourlist-payment-mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: tourlist-payment-mongodb-volume
              mountPath: /data
          envFrom:
            - configMapRef:
                name: tourlist-payment-db-config
            - secretRef:
                name: tourlist-payment-db-secrets
      volumes:
        - name: tourlist-payment-mongodb-volume
          persistentVolumeClaim:
            claimName: tourlist-payment-mongodb-pvc