apiVersion: v1
kind: Service
metadata:
  name: tourlist-payment-service
spec:
  type: ClusterIP
  selector:
    app: tourlist-payment-pod
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-payment-deployment
  labels:
    app: tourlist-payment-pod
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tourlist-payment-pod
  template:
    metadata:
      labels:
        app: tourlist-payment-pod
    spec:
      containers:
        - name: tourlist-payment
          image: ssuyas/tourlist_payment
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: tourlist-payment-config
            - secretRef:
                name: tourlist-payment-secrets

