apiVersion: v1
kind: Service
metadata:
  name: tourlist-checklist-service
spec:
  type: ClusterIP
  selector:
    app: tourlist-checklist-pod
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-checklist-deployment
  labels:
    app: tourlist-checklist-pod
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tourlist-checklist-pod
  template:
    metadata:
      labels:
        app: tourlist-checklist-pod
    spec:
      containers:
        - name: tourlist-checklist
          image: ssuyas/tourlist_checklist:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: tourlist-checklist-config
            - configMapRef:
                name: tourlist-common-config
            - secretRef:
                name: tourlist-checklist-secrets
            - secretRef:
                name: tourlist-common-secrets

