spring:
  messages:
    basename: errors, messages
    encoding: UTF-8
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${USER_NAME}
      password: ${USER_PASSWORD}
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      leak-detection-threshold: 30000
      connection-test-query: SELECT 1
      isolate-internal-queries: false
      validation-timeout: 5000
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jwt:
    secret: ${JWT_KEY}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_REDIRECT_URL}
logging:
  level:
    org:
      hibernate:
        SQL: info
    com:
      eminyidle:
        auth: info
    org.springframework.security: info

social:
  google:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect: ${GOOGLE_REDIRECT_URL}

auth-redirect-url: ${AUTH_REDIRECT_URL}

server:
  port: 8080