apiVersion: v1
kind: Service
metadata:
  name: tourlist-frontend-service
spec:
  type: ClusterIP
  selector:
    app: tourlist-frontend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-frontend-deployment
  labels:
    app: tourlist-frontend-pod
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tourlist-frontend-pod
  template:
    metadata:
      labels:
        app: tourlist-frontend-pod
    spec:
      containers:
        - name: tourlist-frontend
          image: ssuyas/tourlist_frontend
          ports:
            - containerPort: 80

