apiVersion: v1
kind: ConfigMap
metadata:
  name: tourlist-auth-config
data:
  GOOGLE_REDIRECT_URL: "https://tourlist.me/api/auth/login"
  AUTH_REDIRECT_URL: "https://tourlist.me"
  AUTH_DB_URL: "jdbc:mariadb://tourlist-auth-db-service:3306/TOURLIST?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false"
  AUTH_REDIS_HOST: "tourlist-auth-redis-service"
  AUTH_REDIS_PORT: "6379"