spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: tour
  neo4j:
    authentication:
      username: ${FEED_NEO4J_USER_NAME}
      password: ${FEED_NEO4J_USER_PASSWORD}
    uri: ${FEED_NEO4J_URI}
  data:
    mongodb:
      database: ${FEED_MONGO_DB_NAME}
      port: 27018
      user: ${FEED_MONGO_DB_ROOT_USER_NAME}
      password: ${FEED_MONGO_DB_ROOT_USER_PASSWORD}
      uri: mongodb://${FEED_MONGO_DB_ROOT_USER_NAME}:${FEED_MONGO_DB_ROOT_USER_PASSWORD}@${MONGO_HOST}:27018/${DB_NAME}?authSource=admin

logging:
  level:
    com.eminyidle.tour: debug
server:
  port: 8086
