apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-istio
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tourlist.official@gmail.com
    privateKeySecretRef:
      name: letsencrypt-istio
    solvers:
    - http01:
        ingress:
          class: istio