apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1

    ingressGateways:
    - name: istio-ingressgateway #기본게이트웨이
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1

    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1

  meshConfig:
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY

