apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tourlist-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 8443
      name: http
      protocol: HTTP
    hosts:
    - tourlist.me