spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: tour
  neo4j:
    authentication:
      username: neo4j
      password: 20000813
    uri: bolt://localhost:7687

logging:
  level:
    com.eminyidle.place: debug
server:
  port: 8084
