spring:
  application:
    name: checklist
  config:
    import:
      - optional:file:.env[.properties]
  neo4j:
    authentication:
      username: ${CHECKLIST_NEO4J_USER_NAME}
      password: ${CHECKLIST_NEO4J_USER_PASSWORD}
    uri: ${CHECKLIST_NEO4J_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CHECKLIST_CONSUMER_GROUP}

server:
  port: 8087

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
    com:
      eminyidle:
        checklist: DEBUG