apiVersion: v1
kind: Service
metadata:
  name: tourlist-place-db-service
spec:
  selector:
    app: tourlist-place-neo4j-pod
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tourlist-place-neo4j-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-place-neo4j-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourlist-place-neo4j-pod
  template:
    metadata:
      labels:
        app: tourlist-place-neo4j-pod
    spec:
      containers:
        - name: tourlist-place-neo4j
          image: neo4j:5.19.0-community
          ports:
            - containerPort: 7687
          volumeMounts:
            - name: tourlist-place-neo4j-volume
              mountPath: /data
          envFrom:
            - configMapRef:
                name: tourlist-place-db-config
            - secretRef:
                name: tourlist-place-db-secrets
      volumes:
        - name: tourlist-place-neo4j-volume
          persistentVolumeClaim:
            claimName: tourlist-place-neo4j-pvc